### Calculation of the first layer dimensions of the decoder to match the last layer of the encoder (volume)

In [160]:
import numpy as np
import torch.nn as nn
import torch.nn.functional as F

from torch import Tensor

In [163]:
def conv3D_out_shape(shape,padding=0, kernel_size=1, stride=1, dilation=1):
    """
    Return the shape of the 3D array after applying this 3D conv
    """
    return ((shape+ 2*padding - dilation * (kernel_size-1)-1)/stride +1).astype(int)

In [164]:
def convTranspose3D_out_shape(shape,padding=0, kernel_size=1, stride=1, dilation=1):
    """
    Return the shape of the 3D array after applying this 3D conv
    """
    return ((shape-1)*stride + 2*padding - dilation * (kernel_size-1) +1).astype(int)

In [165]:
input_shape = np.array([18, 41, 38])
conv3D_out_shape(input_shape, padding=1, kernel_size=1, stride=2, dilation=1)

array([10, 22, 20])

In [166]:
convTranspose3D_out_shape(np.array([10, 22, 20]), padding=1, kernel_size=1, stride=2, dilation=1)

array([21, 45, 41])

In [201]:
input_shape = np.array([13, 70, 80])
print('Input shape:')
print(input_shape)

print('Encoder')
new_shape = conv3D_out_shape(input_shape, padding=3, kernel_size=7, stride=1)
new_shape = conv3D_out_shape(new_shape, padding=1, kernel_size=3, stride=2)
print(new_shape)

for i in range(2):
    new_shape = conv3D_out_shape(new_shape, padding=1, kernel_size=3, stride=2)
    print(new_shape)

new_shape = conv3D_out_shape(new_shape, padding=3, kernel_size=3, stride=1)
new_shape = conv3D_out_shape(new_shape, padding=1, kernel_size=3, stride=2)

print('Encoder Output shape:')
print(new_shape)
encoder_output_shape = new_shape

print('Decoder')
new_shape = convTranspose3D_out_shape(new_shape, padding=np.array([2,2,2]), kernel_size=3, stride=1)
new_shape = convTranspose3D_out_shape(new_shape, padding=1, kernel_size=3, stride=2)
new_shape = convTranspose3D_out_shape(new_shape, padding=1, kernel_size=3, stride=1)
print(new_shape)
new_shape = convTranspose3D_out_shape(new_shape, padding=1, kernel_size=3, stride=2)
new_shape = convTranspose3D_out_shape(new_shape, padding=1, kernel_size=3, stride=1)
print(new_shape)
new_shape = convTranspose3D_out_shape(new_shape, padding=1, kernel_size=3, stride=2)
print(new_shape)
new_shape = convTranspose3D_out_shape(new_shape, padding=1, kernel_size=3, stride=1)
print('Decoder Output shape:')
print(new_shape)

Input shape:
[13 70 80]
Encoder
[ 7 35 40]
[ 4 18 20]
[ 2  9 10]
Encoder Output shape:
[3 7 7]
Decoder
[ 9 17 17]
[17 33 33]
[33 65 65]
Decoder Output shape:
[33 65 65]
